config/routes.rb
Rails.application.routes.draw do
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  root "top#index"
  get :sign_up, to: 'users#new'
  post :sign_up, to: 'users#create'
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  resources :home, only: %i[index]
  resource :users, only: %i(edit update)
  resources :schedules
  resources :profiles, only: %i(index)
  resource :characters, only: [:edit, :update]
  resource :goal, only: %i(new create edit update) do
    collection do
      post :skip
    end
  end
  resources :steps, only: %i(new create destroy) do
    collection do
      get :edit
      put :update
    end
    post :day_check, on: :member
  end
end

app/models/user.rb
require 'open-uri'
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications
  has_many :schedules, dependent: :destroy
  has_one :goal, dependent: :destroy
  has_many :steps, dependent: :destroy
  has_one :character, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :name, presence: true, length: { maximum: 15 }
  # activestorage-validator による添付画像の検証
  # validates :images,
  # content_type: %i(gif png jpg jpeg),                        # 画像の種類
  # size: { less_than_or_equal_to: 5.megabytes },              # ファイルサイズ
  # dimension: { width: { max: 2000 }, height: { max: 2000 } } # 画像の大きさ

    # ユーザー作成後に呼び出されるコールバック
  after_create :assign_default_character

  private


  # デフォルトキャラクターの属性を持つキャラクターを作成
  def assign_default_character
    # Cloudinaryにアップロード済みのデフォルト画像のURL
    default_image_url = "https://res.cloudinary.com/dkxx3dybs/image/upload/v1702127528/cat_notification_kwprga.png"
    self.create_character(
      name: 'ねこちゃん',
      personality: 'kind',
      communication_style: 'Casual Japanese',
      relationship: 'friend',
      additional: ''
    )

    if self.character.present?
      # Cloudinaryの画像URLからアタッチ
      self.character.image.attach(io: URI.parse(default_image_url).open, filename: 'cat_notification.png')

      # Character インスタンスを保存
      self.character.save!
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:edit, :update]
  before_action :set_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    ActiveRecord::Base.transaction do
      if @user.save
        # 初回ログイン時のみ目標設定画面へリダイレクト
        @user.update!(first_login: false) # `update!`を使用してエラーが発生した場合に例外を投げる
        auto_login(@user)
        flash[:notice] = 'ユーザー登録が完了しました'
        redirect_to new_goal_path
      else
        render :new, status: :unprocessable_entity
      end
    end
  rescue ActiveRecord::RecordInvalid
    render :new, status: :unprocessable_entity
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'ユーザー情報を更新しました'
      redirect_to profiles_path
    else
      flash.now[:alert] = 'ユーザー情報の更新に失敗しました'
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<main class="container mx-auto flex justify-center">
  <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
      <h2 class="mt-10 text-center text-2xl font-sans leading-9 tracking-tight text-gray-900">ユーザー情報変更</h2>
    </div>

    <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
      <%= form_with model: @user, url: users_path, local: true, class: "space-y-6" do |f| %>
        <%= render 'shared/error_messages', object: @user %>
        <div>
          <%= f.label :name, t('activerecord.attributes.user.name'), class: "leading-7 text-sm text-gray-600" %>
          <%= f.text_field :name, required: true, class: "input input-bordered input-accent w-full max-w-xs" %>
        </div>

        <div>
          <%= f.label :email, t('activerecord.attributes.user.email'), class: "leading-7 text-sm text-gray-600" %>
          <%= f.email_field :email, required: true, class: "input input-bordered input-accent w-full max-w-xs" %>
        </div>

        <div class="flex justify-center p-7">
          <%= f.submit "更新する", class: "btn btn-accent w-full" %>
        </div>

        <div class="flex justify-center link link-warning">
          <%= link_to "ホームに戻る", home_index_path %>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/users/new.html.erb
<main class="container mx-auto flex justify-center">
  <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
      <h2 class="mt-10 text-center text-2xl font-sans leading-9 tracking-tight text-gray-900">ユーザー登録</h2>
    </div>

    <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
      <%= form_with model: @user, url: sign_up_path, local: true, class: "space-y-6" do |f| %>
        <%= render 'shared/error_messages', object: @user %>
        <div>
          <%= f.label :name, t('activerecord.attributes.user.name'), class: "leading-7 text-sm text-gray-600" %>
          <%= f.text_field :name, required: true, class: "input input-bordered input-accent w-full max-w-xs" %>
        </div>

        <div>
          <%= f.label :email, t('activerecord.attributes.user.email'), class: "leading-7 text-sm text-gray-600" %>
          <%= f.email_field :email, required: true, class: "input input-bordered input-accent w-full max-w-xs" %>
        </div>

        <div>
          <%= f.label :password, t('activerecord.attributes.user.password'), class: "leading-7 text-sm text-gray-600" %>
          <%= f.password_field :password, required: true, class: "input input-bordered input-accent w-full max-w-xs" %>
        </div>

        <div>
          <%= f.label :password_confirmation, t('activerecord.attributes.user.password_confirmation'), class: "leading-7 text-sm text-gray-600" %>
          <%= f.password_field :password_confirmation, required: true, class: "input input-bordered input-accent w-full max-w-xs" %>
        </div>

        <div class="flex justify-center p-7">
          <%= f.submit "登録する", class: "btn btn-accent w-full w-full" %>
        </div>
        <div class="flex justify-center ">
          <%= link_to '', auth_at_provider_path(provider: :line), class: 'button-img' %>
        </div>

        <div class="flex justify-center link link-success">
          <%= link_to "ログインページへ", login_path %>
        </div>
      <% end %>
    </div>
  </div>
</main>