config/routes.rb
Rails.application.routes.draw do
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  root "top#index"
  get :sign_up, to: 'users#new'
  post :sign_up, to: 'users#create'
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  resources :home, only: %i[index]
  resource :users, only: %i(edit update)
  resources :schedules
  resources :profiles, only: %i(index)
  resource :characters, only: [:edit, :update]
  resource :goal, only: %i(new create edit update) do
    collection do
      post :skip
    end
  end
  resources :steps, only: %i(new create destroy) do
    collection do
      get :edit
      put :update
    end
    post :day_check, on: :member
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  # スケジュールのidをハッシュ化
  include Hashid::Rails
  belongs_to :user
  # スケジュールが削除されたときに関連するタスクも一緒に削除
  has_many :tasks, inverse_of: :schedule, dependent: :destroy
  # 同フォーム内で複数モデルを取り扱う スケジュールを作成または更新する際に、関連するタスクも一緒に作成または更新
  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: {message: "スケジュール名を入力してください"},  length: { maximum: 255 }
  validates :day_of_week, presence: {message: "曜日を選択してください"}
  # ユーザーが同じ曜日に複数のスケジュールを作成できないようにする
  validate :unique_day_of_week_per_user

  private

  def unique_day_of_week_per_user
    # 現在のユーザーが持っているスケジュールの曜日を取得（編集しているスケジュールは除く）
    existing_days = user.schedules.where.not(id: id).pluck(:day_of_week).flatten
    # 新しく作成または更新しようとしているスケジュールの曜日
    new_days = day_of_week
    # 既存のスケジュールと新しいスケジュールで重複する曜日があるか確認
    if (existing_days & new_days).any?
      errors.add(:base, '各曜日につき一つだけスケジュールを作成できます')
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :require_login
  before_action :set_schedule, only: %i(update destroy)
  before_action :set_task, only: %i(show edit)
  def index
    @schedules = current_user.schedules.all
  end

  def new
    @schedule = Schedule.new
    @task = @schedule.tasks.build
  end

  def create
    # tasks_attributes をハッシュから配列に変換
    tasks_attributes_array = params[:schedule][:tasks_attributes].values

    tasks_attributes_array.each do |task_attributes|
      if task_attributes["task_time(4i)"].blank? || task_attributes["task_time(5i)"].blank?
        @schedule = current_user.schedules.build(schedule_params)
        @schedule.errors.add(:base, 'タスクを行う時間を入力してください')
        flash.now[:alert] = 'スケジュールの作成に失敗しました。'
        render :new, status: :unprocessable_entity
        return
      end
    end

    # 配列をソート
    sorted_tasks_attributes = tasks_attributes_array.sort_by do |task_attributes|
      task_time_hour = task_attributes["task_time(4i)"].to_i
      task_time_minute = task_attributes["task_time(5i)"].to_i
      task_time_hour * 60 + task_time_minute
    end

    # ソートされた配列を再度ハッシュ形式に変換
    sorted_tasks_hash = sorted_tasks_attributes.each_with_index.map { |attrs, index| [index.to_s, attrs] }.to_h

    # 新しいパラメータとしてマージ
    merged_params = schedule_params.merge(tasks_attributes: sorted_tasks_hash)

    @schedule = current_user.schedules.build(merged_params)

    if @schedule.save
      flash[:notice] = 'スケジュールを作成しました'
      redirect_to schedule_path(@schedule)
    else
      flash.now[:alert] = 'スケジュールの作成に失敗しました。'
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    params[:schedule][:tasks_attributes].each do |_, task_attributes|
      if task_attributes["task_time(4i)"].blank? || task_attributes["task_time(5i)"].blank?
        @schedule.errors.add(:base, 'タスクを行う時間を入力してください')
        render :edit, status: :unprocessable_entity
        return
      end
    end

    if @schedule.update(schedule_params)
      # task_time順で並び替えてpositionカラムを更新
      @schedule.tasks.order(:task_time).each.with_index(1) do |task, index|
        task.update_column(:position, index)
      end
      flash[:notice] = 'スケジュールを更新しました'
      redirect_to schedule_path(@schedule)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @schedule.destroy
    redirect_to schedules_path
  end

  private

  def set_schedule
    @schedule = current_user.schedules.find_by_hashid(params[:id])
  end

  def set_task
    @schedule = current_user.schedules.find_by_hashid(params[:id])
    @tasks = @schedule.tasks.order(:task_time)
  end

  def schedule_params
    params.require(:schedule).permit(:name, day_of_week: [],
                                    tasks_attributes: [:id, :task_time, :to_do, :memo, :goal_select, :position, :_destroy])
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<main class="box51 m-0 sm:m-10" >
  <%= form_with(model: schedule, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class=" mx-auto">
      <div class="flex justify-center m-10">
        <%= f.text_field :name, placeholder: "スケジュール名", class:'input input-bordered input-primary w-3/4 lg:w-1/2 text-center', required:true %>
      </div>
      <div class="flex flex-col lg:flex-row lg:justify-center">
        <div class="flex justify-center items-center whitespace-nowrap mb-5 lg:mt-0 lg:ml-8">
          <%= button_tag '▼ 全選択', type: 'button', id: 'select-all', class: 'btn btn-accent mr-2' %>
          <%= button_tag '▽ 全解除', type: 'button', id: 'deselect-all', class: 'btn btn-secondary' %>
        </div>
        <div class="flex justify-center flex-wrap">
          <% ['日', '月', '火', '水', '木', '金', '土'].each_with_index do |day, index| %>
            <div class=" px-2 flex items-center justify-start overflow-auto">
              <%= check_box_tag 'schedule[day_of_week][]', index, schedule.day_of_week.include?(index), class: 'checkbox checkbox-primary m-2' %>
              <%= day %>
            </div>
          <% end %>
        </div>

      </div>
    </div>
    <div class="form-group justify-center mt-5" id="tasks-container">
      <%= f.fields_for :tasks, @tasks do |task| %>
        <%= render 'task_fields', f: task %>
      <% end %>
    </div>
    <div class="flex justify-center p-8">
      <%= link_to_add_association raw('<i class="fa-solid fa-circle-plus"></i> 追加'), f, :tasks, class:"btn btn-accent" %>
    </div>

    <div class="flex flex-col sm:flex-row justify-center">
      <button class="btn btn-primary mb-2 sm:mb-0 sm:mr-2" type="button" id="sort-tasks-button"><i class="fa-solid fa-arrow-right-arrow-left fa-rotate-90"></i> 時間順に並び替える</button>
      <button class="btn btn-active btn-accent sm:mt-0" type="submit"><i class="fa-solid fa-check"></i> スケジュールを保存する</button>
    </div>
  <% end %>
</main>

app/views/schedules/_schedule.html.erb
<div class="box51 w-full mx-auto m-10 md:w-2/3">
  <p class="leading-relaxed text-xl">
    <strong>スケジュール名:</strong>
    <p><%= schedule.name %></p>
  </p>
  <span class="inline-block h-1 w-full rounded bg-red-300 mt-8 mb-6"></span>
  <p class="text-xl">
    <strong>一日の予定</strong>
  </p>
  <div class="container w-1/3  mx-auto text-left">
    <% tasks.each do |i| %>
      <ul>
        <td><%= i.task_time.strftime("%H:%M") %></td>
        <td><%= i.to_do %></td>
        <td><%= i.memo %></td>
      </ul>
    <% end %>
  </div>
</div>

app/views/schedules/_task_fields.html.erb
<div class="nested-fields flex justify-center">
  <div class="form-group space-x-1 space-y-3 mb:space-y-0 justify-center flex flex-wrap">
    <div class="box58">
      <%= f.time_select :task_time, { minute_step: 15, default: nil, include_blank: true }, class:'input input-bordered input-primary w-20 max-w-xs mb-3', required:true %>
      <%= f.text_field :to_do, placeholder: "タスク", class: 'input input-bordered input-primary max-w-xs mb-3', required:true %>
      <%= f.text_field :memo, placeholder: "メモ", class: 'input input-bordered input-primary max-w-xs mb-3' %>
      <%= link_to_remove_association raw('<i class="fa-solid fa-trash"></i> 削除'), f, class: 'btn btn-outline btn-error' %>
    </div>
  </div>
</div>

app/views/schedules/edit.html.erb
<%= render 'form', { schedule: @schedule, task: @task } %>

app/views/schedules/index.html.erb
<section>
  <div class="container px-5 py-24 mx-auto">
    <div class="w-full mx-auto text-center">
      <div class="box51 w-full mx-auto m-10 md:w-2/3">
        <h1 class="text-xl">あなたのスケジュール</h1>

        <div>
          <% @schedules.each do |schedule| %>
            <div class="p-4 flex flex-col">
              <%= link_to schedule.name , schedule, class:"bg-blue-50 hover:bg-blue-100 hover:text-blue-600 text-blue-500 rounded-full" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="p-5 flex flex-col sm:flex-row justify-center items-center">
        <%= link_to raw('<i class="fa-solid fa-dove"></i> 新しくスケジュールを作成する'), new_schedule_path, class: 'btn btn-accent m-3' %> |
        <%= link_to raw('<i class="fa-solid fa-house"></i> ホームへ'), home_index_path, class: 'btn btn-secondary m-3' %>
      </div>
    </div>
  </div>
</section>

app/views/schedules/new.html.erb
  <%= render "form", { schedule: @schedule } %>

app/views/schedules/show.html.erb
<section>
  <div class="container px-5 py-24 mx-auto">
    <div class="w-full mx-auto text-center">
      <%= render 'schedule', {schedule: @schedule, tasks: @tasks} %>

      <div class="p-5 flex flex-col sm:flex-row justify-center items-center">
        <%= link_to raw('<i class="fa-solid fa-pencil"></i> 編集する'), edit_schedule_path(@schedule), class: 'btn bg-yellow-100 m-3' %> |
        <%= link_to raw('<i class="fa-solid fa-list"></i> スケジュール一覧へ'), schedules_path, class: 'btn btn-primary m-3' %> |
        <%= link_to raw('<i class="fa-solid fa-house"></i> ホームへ'), home_index_path, class: 'btn btn-secondary m-3' %>
      </div>
      <%= button_to raw('<i class="fa-solid fa-trash"></i> スケジュールを削除する'), @schedule, method: :delete, class: 'btn btn-outline btn-error mt-10', data: { turbo_confirm: 'スケジュールを削除してもよろしいですか？' } %>
    </div>
  </div>
</section>