config/routes.rb
Rails.application.routes.draw do
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  root "top#index"
  get :sign_up, to: 'users#new'
  post :sign_up, to: 'users#create'
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  resources :home, only: %i[index]
  resource :users, only: %i(edit update)
  resources :schedules
  resources :profiles, only: %i(index)
  resource :characters, only: [:edit, :update]
  resource :goal, only: %i(new create edit update) do
    collection do
      post :skip
    end
  end
  resources :steps, only: %i(new create destroy) do
    collection do
      get :edit
      put :update
    end
    post :day_check, on: :member
  end
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :step

end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :goal
  has_one :achievements
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  has_many :steps
  accepts_nested_attributes_for :steps
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  # スケジュールのidをハッシュ化
  include Hashid::Rails
  belongs_to :user
  # スケジュールが削除されたときに関連するタスクも一緒に削除
  has_many :tasks, inverse_of: :schedule, dependent: :destroy
  # 同フォーム内で複数モデルを取り扱う スケジュールを作成または更新する際に、関連するタスクも一緒に作成または更新
  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: {message: "スケジュール名を入力してください"},  length: { maximum: 255 }
  validates :day_of_week, presence: {message: "曜日を選択してください"}
  # ユーザーが同じ曜日に複数のスケジュールを作成できないようにする
  validate :unique_day_of_week_per_user

  private

  def unique_day_of_week_per_user
    # 現在のユーザーが持っているスケジュールの曜日を取得（編集しているスケジュールは除く）
    existing_days = user.schedules.where.not(id: id).pluck(:day_of_week).flatten
    # 新しく作成または更新しようとしているスケジュールの曜日
    new_days = day_of_week
    # 既存のスケジュールと新しいスケジュールで重複する曜日があるか確認
    if (existing_days & new_days).any?
      errors.add(:base, '各曜日につき一つだけスケジュールを作成できます')
    end
  end
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :user
  belongs_to :goal
  has_many :achievements, dependent: :destroy

  # 0より大きい整数を確認
  # actionが入力されている場合のみ適用
  validates :times_set, numericality: { only_integer: true, greater_than: 0, message: "" }, if: :action_present?

  # actionとtimes_setは両方データが入っているか確認
  validate :custom_action_presence
  validate :custom_times_set_presence

  #step作成と同時にachivementモデルも作成する(当日含め過去7日分)
  def create_achievements!
    6.downto(0) do |n|
      achievements.create!(daily: Date.today - n)
    end
  end

  private

  def custom_action_presence
    if times_set.present? && action.blank?
      errors.add(:base, "頑張ることを入力してください")
    end
  end

  def custom_times_set_presence
    if action.present? && times_set.blank?
      errors.add(:base, "回数を入力してください")
    end
  end

  def action_present?
    action.present?
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :schedule

  validates :task_time, presence: {message: "タスクを行う時間を入力してください"}
  validates :to_do, presence: {message: "タスクを入力してください"}
  # validate :task_time_presense

  private

  def task_time_presense
    if task_time.blank? || task_time.hour.blank? || task_time.min.blank?
      errors.add(:task_time, 'タスクを行う時間を入力してください')
    end
  end
end

app/models/user.rb
require 'open-uri'
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications
  has_many :schedules, dependent: :destroy
  has_one :goal, dependent: :destroy
  has_many :steps, dependent: :destroy
  has_one :character, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :name, presence: true, length: { maximum: 15 }
  # activestorage-validator による添付画像の検証
  # validates :images,
  # content_type: %i(gif png jpg jpeg),                        # 画像の種類
  # size: { less_than_or_equal_to: 5.megabytes },              # ファイルサイズ
  # dimension: { width: { max: 2000 }, height: { max: 2000 } } # 画像の大きさ

    # ユーザー作成後に呼び出されるコールバック
  after_create :assign_default_character

  private


  # デフォルトキャラクターの属性を持つキャラクターを作成
  def assign_default_character
    # Cloudinaryにアップロード済みのデフォルト画像のURL
    default_image_url = "https://res.cloudinary.com/dkxx3dybs/image/upload/v1702127528/cat_notification_kwprga.png"
    self.create_character(
      name: 'ねこちゃん',
      personality: 'kind',
      communication_style: 'Casual Japanese',
      relationship: 'friend',
      additional: ''
    )

    if self.character.present?
      # Cloudinaryの画像URLからアタッチ
      self.character.image.attach(io: URI.parse(default_image_url).open, filename: 'cat_notification.png')

      # Character インスタンスを保存
      self.character.save!
    end
  end
end

app/helpers/categories_helper.rb
module SchedulesHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
  def select_field(field, prompt, choices, form)
    label = form.label field, prompt, class: "leading-7 text-sm text-gray-600"
    select = form.select field, choices, {}, required: true, class: "w-full bg-white rounded border border-gray-300 focus:ring-2 focus:ring-indigo-600 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
    content_tag(:div, label + select)
  end

  # 日本語訳のためのメソッド
  def display_personality(personality_key)
    personalities = {
      'frisky' => '明るい',
      'kind' => '優しい',
      'strict' => '厳しい',
      'amusing' => '面白い',
      'polite' => '礼儀正しい',
      'affectionate' => '愛情深い',
      'gracious' => '上品'
    }
    personalities[personality_key] || '不明'
  end

  def display_communication_style(communication_style_key)
    communication_styles = {
      'Casual Japanese' => '友達口調',
      'Polite Japanese' => '敬語',
      'tone of command' => '命令口調'
    }
    communication_styles[communication_style_key] || '不明'
  end

  def display_relationship(relationship_key)
    relationships = {
      'friend' => '友達',
      'family' => '家族',
      'senior' => '先輩',
      'junior' => '後輩',
      'boyfriend' => '恋人"男性"',
      'girlfriend' => '恋人"女性"'
    }
    relationships[relationship_key] || '不明'
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  # 現在の曜日のスケジュールを取得するメソッド
  def current_day_schedules(user)
    # 現在の曜日を取得（0:日曜日, 1:月曜日, ..., 6:土曜日）
    current_day_of_week = Time.current.wday
    # ユーザーが作成したスケジュールを取得
    # day_of_weekは配列。例えばユーザーが平日や休日として同じスケジュールを設定できるようにするため
    user.schedules.includes(:tasks).where('day_of_week @> ARRAY[?]::integer[]', current_day_of_week)
  end

  # 次の曜日のスケジュールを取得するメソッド
  def next_day_schedules(user)
    next_day_of_week = (Time.current.wday + 1) % 7
    user.schedules.includes(:tasks).where('day_of_week @> ARRAY[?]::integer[]', next_day_of_week)
  end

  # 現在のタスクと次のタスクを取得するメソッド
  def current_and_next_tasks(schedules)
    # 現在の時間を取得
    current_time = Time.current.strftime("%H:%M")
    tasks = schedules.map(&:tasks).flatten.sort_by(&:task_time)
    current_task = tasks.select { |task| task.task_time.strftime("%H:%M") <= current_time }.last
    next_task = tasks.select { |task| task.task_time.strftime("%H:%M") > current_time }.first
    [current_task, next_task]
  end
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/step_helper.rb
module StepHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
    <ul class="flex flex-col mb-0">
      <% object.errors.each do |error| %>
        <% if error.full_message.present? %>
          <li><%= error.full_message %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_massages.html.erb
<% flash.each do |type, msg| %>
  <% if type == 'notice' %><!--操作成功-->
    <div class="flex items-center p-4 mb-4 text-sm text-green-800 border border-green-300 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400 dark:border-green-800" role="alert">
      <span class="font-medium"><i class="fa-solid fa-circle-check"></i> <%= msg %></span>
    </div>
  <% elsif type == 'alert' %><!--警告・注意-->
    <div class="flex items-center p-4 mb-4 text-sm text-red-800 border border-red-300 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400 dark:border-red-800" role="alert">
      <span class="font-medium"><i class="fa-solid fa-circle-xmark"></i> <%= msg %></span>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-gray-600 body-font bottom-0">
  <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
    <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
      <span class="ml-3 text-xl">Yori yoi</span>
    </a>
    <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">© 2023 Yori yoi —
      <a href="https://twitter.com/muimui_moi" class="text-gray-600 ml-1" rel="noopener noreferrer" target="_blank">@muimui_moi</a>
    </p>
    <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
      <%= link_to '利用規約', "#", class: 'link link-hover my-1 text-gray-500' %>
    </span>
    <span class="inline-flex sm:ml-auto sm:mt-0 mt-2 justify-center sm:justify-start">
      <%= link_to 'プライバシーポリシー', "#", class: 'link link-hover my-1 text-gray-500' %>
    </span>
    <span class="inline-flex sm:ml-auto sm:mt-0 mt-2 justify-center sm:justify-start">
      <%= link_to 'お問い合わせ', "#", class: 'link link-hover my-1 text-gray-500', target: '_blank' %>
      <a href="https://twitter.com/muimui_moi" rel="noopener noreferrer" class="text-gray-600 ml-1" target="_blank">
        <i class="fa-brands fa-twitter pt-2"></i>
      </a>
    </span>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="navbar bg-base-100">
  <div class="flex-1">
    <% if logged_in? %>
      <%= link_to home_index_path do %>
        <%= image_tag 'yoriyoi_logo.png', draggable: "false", size: '142x40', class: 'ml-3' %>
      <% end %>
    <% else %>
      <%= link_to root_path do %>
        <%= image_tag 'yoriyoi_logo.png', draggable: "false", size: '142x40', class: 'ml-3' %>
      <% end %>
    <% end %>
  </div>
  <% if logged_in? %>
    <details class="dropdown dropdown-end">
      <summary class="m-1 btn">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-5 h-5 stroke-current">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
        </svg>
      </summary>
      <ul tabindex="0" class="bg-base-200 dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-100">
        <li class="p-3"><%= link_to raw('<i class="fa-solid fa-dove"></i> スケジュールを作成する'), new_schedule_path %></li>
        <li class="p-3"><%= link_to raw('<i class="fa-solid fa-list"></i><i class="fa-solid fa-pencil"></i> スケジュールの確認・編集'), schedules_path %></li>
        <li class="p-3"><%= link_to raw('<i class="fa-solid fa-house-user"></i> マイページ・各種設定'), profiles_path %></li>
        <li class="p-3"><%= link_to raw('<i class="fa-solid fa-right-from-bracket"></i> ログアウト'), logout_path, class: 'nav-link', data: { turbo_method: :delete ,turbo_confirm: 'ログアウトします' } %></li>
      </ul>
    </details>
  <% else %>
    <details class="dropdown dropdown-end">
      <summary class="m-1 btn">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-5 h-5 stroke-current">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
        </svg>
      </summary>
      <ul tabindex="0" class="bg-base-200 dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52">
        <li class="p-3"><%= link_to raw('<i class="fa-solid fa-right-to-bracket"></i> ログイン'), login_path %></li>
        <li class="p-3"><%= link_to raw('<i class="fa-solid fa-user-plus"></i> ユーザー登録'), sign_up_path %></li>
        <li class="p-3"><%= link_to raw('<i class="fa-regular fa-circle-question"></i> お問い合わせ'), "#" %></li>
      </ul>
    </details>
  <% end %>
</header>