config/routes.rb
Rails.application.routes.draw do
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  root "top#index"
  get :sign_up, to: 'users#new'
  post :sign_up, to: 'users#create'
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  resources :home, only: %i[index]
  resource :users, only: %i(edit update)
  resources :schedules
  resources :profiles, only: %i(index)
  resource :characters, only: [:edit, :update]
  resource :goal, only: %i(new create edit update) do
    collection do
      post :skip
    end
  end
  resources :steps, only: %i(new create destroy) do
    collection do
      get :edit
      put :update
    end
    post :day_check, on: :member
  end
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  has_many :steps
  accepts_nested_attributes_for :steps
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_login
  before_action :set_goal, only: %i(edit update)

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to new_step_path #初回のみ/steps/new
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @goal.update(goal_params)
      if params[:home]
        flash[:notice] = '目標を編集しました'
        redirect_to home_index_path
      elsif params[:step]
        flash[:notice] = '目標を編集しました'
        redirect_to edit_steps_path
      else
        render :edit
      end
    else
      render :edit
    end
  end

  def skip
    Goal.transaction do
      goal = Goal.new(user_id: current_user.id)
      goal.save!

      3.times do
        step = Step.new(user_id: current_user.id, goal_id: @goal.id)
        step.save!
        step.create_achievements!
      end
    end
    flash[:notice] = 'まずはスケジュールを作成してみてにゃ'
    redirect_to home_index_path
  rescue ActiveRecord::RecordInvalid
    render :new
  end

  private

  def set_goal
    @goal = current_user.goal
  end

  def goal_params
    params.require(:goal).permit(:ideal_self)
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_goal_section.html.erb
<div class="box75 w-full">
  <div class="box-title">理想のあなた</div>
  <div class="m-5 text-base sm:text-lg">
    <div class="flex justify-end right-0">
      <%= link_to raw('<i class="fa-solid fa-pencil"></i>'), edit_goal_path, class: 'btn bg-yellow-100' %>
    </div>
    <% if goal.ideal_self.blank? %>
      <p>目標を設定してほしいにゃ。</p>
    <% else %>
      <ul class="list-inside my-3">
        <li><i class="fa-brands fa-pagelines" style="color: #319674;"></i> <%= goal.ideal_self %></li>
      </ul>
    <% end %>
  </div>
</div>

app/views/goals/edit.html.erb
<section>
  <div class="container mx-auto">
    <div class="text-center">
      <div class="box51 w-full mx-auto m-10 md:w-2/3">
        <div class="chat chat-start flex items-end justify-start">
          <div>
            <%= image_tag "cat_information.png", class: 'w-24 rounded-full ring' %>
          </div>
          <div class="chat-bubble bg-gray-50 w-full mx-auto m-5">キミがなりたい理想のジブンを教えてほしいにゃ♪</div>
        </div>

        <div class="justify-center">
        <%= form_with model: @goal, url: goal_path, local: true do |f| %>
          <%= f.text_field :ideal_self, placeholder: "例 : 今の体重から5キロ痩せたい...など", class: 'input input-bordered w-full max-w-lg mt-10 text-center' %>
          <div class="p-5 flex flex-col sm:flex-row justify-center items-center">
            <%= button_tag(type:'submit', name:'home', class: "btn btn-accent m-2") do %>
              <i class="fa-solid fa-check"></i> 登録
            <% end %>|
            <%= button_tag(type:'submit', name:'step', class:"btn btn-secondary m-2") do %>
              <i class="fa-solid fa-fire"></i> 頑張ることリストの作成
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="p-5 flex flex-col sm:flex-row justify-center items-center">
      <%= link_to raw('<i class="fa-solid fa-house"></i> ホームへ'), home_index_path, class: 'btn btn-outline btn-secondary mt-10' %>
    </div>
  </div>
</section>

app/views/goals/new.html.erb
<section>
  <div class="container mx-auto">
    <div class="text-center">
      <div class="box51 w-full mx-auto m-10">
        <div class="chat chat-start flex items-end justify-start">
          <div>
            <%= image_tag "cat_information.png", class: 'w-24 rounded-full ring' %>
          </div>
          <div id="textbox" class="chat-bubble bg-gray-50 w-full mx-auto m-5">
            <div>はじめまして！ 登録してくれてありがとにゃ〜！</div>
            <div>これから一緒にがんばるにゃ</div>
            <div>まずは、キミがなりたい理想のジブンを教えてほしいにゃ！</div>
          </div>
        </div>
        <div class="justify-center">
        <%= form_with model: @goal, url: goal_path, local: true do |f| %>
          <%= f.text_field :ideal_self, placeholder: "例 : 今の体重から5キロ痩せたい...など", class: 'input input-bordered w-full max-w-lg text-center' %>
          <div class="p-5 flex flex-col sm:flex-row justify-center items-center">
            <%= button_tag(type:'submit', class:"btn btn-accent m-2") do %>
              <i class="fa-solid fa-check"></i> 登録
            <% end %>
          </div>
        <% end %>
        <%= button_to raw('<i class="fa-solid fa-angles-right"></i> あとで設定する'), skip_goal_path, class:"btn btn-primary m-2" %>
      </div>
    </div>
  </div>
</section>

app/views/goals/show.html.erb
<section class="md:mr-2 w-full md:w-1/2 flex flex-col relative overflow-auto" style="height: 40rem; border: dotted 2px #f7e9e8; padding: 1rem;">
  <%= render 'goals/goal_section', goal: goal %>
  <%= render 'steps/steps_section', steps: steps %>
</section>